### ISSUE TITLE
Ошибка в загрузке теста с кирилицей

### ISSUE THREAD

**Issue by OtakuDocotor** [KBR4/HistoryEGEProject#1]
1.Создаём файл с тестом
![image](https://github.com/KBR4/HistoryEGEProject/assets/132132403/0e5439dd-d483-4ee7-b4a4-13765e534ae7)
2. Добавляем его в тест
![image](https://github.com/KBR4/HistoryEGEProject/assets/132132403/47799a21-f00a-4233-87c6-44d321c6cf5b)

**Comment by KBR4** [comment]
да да проблемы с кодировкой (по необъяснимым причинам)
придется вставить форс кодировки 1251

Вероятно придется перейти к .json файлам

**Comment by KBR4** [comment]
Исправлено
