### ISSUE TITLE
Для удобства нужно не позволять пользователю создавать тест, если нет ни одного раздела

### ISSUE THREAD

**Issue by OtakuDocotor** [KBR4/HistoryEGEProject#2]
1)Если я создаю тест и при этом у меня нет ни одного раздела мне выдаёт ошибку
![image](https://github.com/KBR4/HistoryEGEProject/assets/132132403/e8fe0965-c23c-4cfb-905b-29cdacb3bf61)
2) При этом удаляя всё то что я загружал для добавления теста 
Лучше было бы вообще не пускать пользователя туда пока нет раздела либо говорить заранее чтобы он не тратил время на бесполезное добавление карт и тестовых файлов которое в конечном счёте выведет его на ошибку

**Comment by KBR4** [comment]
Исправлено, теперь требуется выбрать раздел перед тем как юзеру будет позволено создавать тест
