### ISSUE TITLE
Если карта загружена и мы хотим её поменять и жмём на закрытие предыдущая загруженная карта стирается (Просто придирка))) )  

### ISSUE THREAD

**Issue by OtakuDocotor** [KBR4/HistoryEGEProject#3]
1. Загружаем карту 
![image](https://github.com/KBR4/HistoryEGEProject/assets/132132403/255c645a-39c0-46d0-ba26-df3bad94361b)
2. Загружаем другую 
![image](https://github.com/KBR4/HistoryEGEProject/assets/132132403/dc03fd5a-dc93-4457-ace9-5952af0a5a54)
передумали закрываем
3. Предыдущая загруженная пропадает
![image](https://github.com/KBR4/HistoryEGEProject/assets/132132403/ca461148-4e83-4255-9f66-4416b58b44b5)

**Comment by KBR4** [comment]
Исправлено. Теперь картинка (и соовтетственно путь к ней) не обновляются при нажатии Отмена при повторном выборе картинки.
