### ISSUE TITLE
Могу добавить абсолютно одинаковые тесты (по названию содержанию и карте)

### ISSUE THREAD

**Issue by OtakuDocotor** [KBR4/HistoryEGEProject#4]
![image](https://github.com/KBR4/HistoryEGEProject/assets/132132403/33721892-f4dc-4131-94b4-ad3e795bb708)

**Comment by KBR4** [comment]
Исправлено. Тесты теперь требуют разные названия, когда находятся в одном разделе. За наполнение контента ответственным является юзер, тем более, что возможно создание разных тестов по одной и той же карте.
