### ISSUE TITLE
Если пароль больше чем ограничение строки то мы его никогда не введём (Опять же просто придирка но я пишу всё что найду даже такие мелочи)  

### ISSUE THREAD

**Issue by OtakuDocotor** [KBR4/HistoryEGEProject#5]
![image](https://github.com/KBR4/HistoryEGEProject/assets/132132403/5415735f-8c43-4761-977b-997bd345efd8)

**Comment by KBR4** [comment]
App.config защищенное и неизменяемое место, изменения не требуются, пароль будет установлен по предварительному согласию в рамках установленной длины
