### ISSUE TITLE
При нажатии кнопки назад в выборе теста всё равно загружает тест на который мы нажимали чтобы посмотреть карту и вопросы 

### ISSUE THREAD

**Issue by OtakuDocotor** [KBR4/HistoryEGEProject#9]
1. Нажимаем выбрать тест
![image](https://github.com/KBR4/HistoryEGEProject/assets/132132403/78dbe41b-1783-4f48-a046-bea829ddbd37)
2. Нажимаем на раздел и тест
![image](https://github.com/KBR4/HistoryEGEProject/assets/132132403/28f888a1-f659-4376-9b3c-67b2da9d9fd2)
3. Нажимаем кнопку назад
![image](https://github.com/KBR4/HistoryEGEProject/assets/132132403/efa80603-6be8-442d-b53d-6437543cd85a)
Ииииии вот
![image](https://github.com/KBR4/HistoryEGEProject/assets/132132403/e59c30ff-d54e-4eb1-b4da-be19b6991510)

**Comment by KBR4** [comment]
Исправлено. Также исправлена ошибка, связанная с неправильной работой информационной панели при нажатии кнопки выбора нового теста, а затем нажатии кнопки "Назад".
